server:
  port: ${port:10047}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PWD:test123}
    driver-class-name: ${DATASOURCE_DRIVERCLASS:org.postgresql.Driver}

#routing:
#  header: testHeader
#message:
#  xpath:
#    mappings:
#      pacs.004.001.10: ${PACS004_BATCH_XPATH:"(.//*[local-name()='RmtInf']//*[local-name()='Ustrd'])[1]"}
#processor:
#  pacs.004.001.10: ${PACS004PROCESSOR:pacs004processor}

topic:
  dispatchertopic: ${DISPATCHERTOPIC:DISPATCHERTOPIC}
  errortopic: ${EPH:EPH}
  fctopic: ${FCTOPIC:FCTOPIC}
  ephtopic: ${EPHTOPIC:EPHTOPIC}
  sfmstopic: ${SFMSTOPIC:SFMSTOPIC}


