server:
  port: ${port:1047}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PWD:test123}
    driver-class-name: ${DATASOURCE_DRIVERCLASS:org.postgresql.Driver}
#  kafka:
#    listener:
#    concurrency: 1
#    consumer:
#      properties:
#        bootstrap.servers: 34.28.251.45:9092
#        #34.28.251.45:9092
#        #20.192.24.194:39092
#        auto.offset.reset: earliest
#        key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
#        value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    producer:
#      properties:
#        bootstrap.servers: 34.28.251.45:9092
#        key.serializer: org.apache.kafka.common.serialization.StringSerializer
#        value.serializer: org.apache.kafka.common.serialization.StringSerializer
#        enable.auto.commit: false
#        missing.topics.fatal: false
#
#routing:
#  header: testHeader
#message:
#  xpath:
#    mappings:
#      pacs.004.001.10: ${PACS004_BATCH_XPATH:"(.//*[local-name()='RmtInf']//*[local-name()='Ustrd'])[1]"}
#processor:
#  pacs.004.001.10: ${PACS004PROCESSOR:pacs004processor}

topic:
  dispatchertopic: ${DISPATCHERTOPIC:DISPATCHERTOPIC}
  errortopic: ${EPH:EPH}
  fctopic: ${FCTOPIC:FCTOPIC}
  ephtopic: ${EPHTOPIC:EPHTOPIC}
  sfmstopic: ${SFMSTOPIC:SFMSTOPIC}
  pacs.004.001.10: ${PACS004TOPIC:pacs004Topic}

