server:
  port: ${port:8089}

logging:
  level:
    root: ${loglevel:INFO}
    #DEBUG

spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://34.135.239.235:5432/postgresdb}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PWD:test123}
    driver-class-name: ${DATASOURCE_DRIVERCLASS:org.postgresql.Driver}

topic:
  dispatchertopic: ${DISPATCHERTOPIC:DISPATCHERTOPIC}
  errortopic: ${EPH:EPH}
  fctopic: ${FCTOPIC:FCTOPIC}
  ephtopic: ${EPHTOPIC:EPHTOPIC}
  sfmstopic: ${SFMSTOPIC:SFMSTOPIC}

